/**
 * The vendored copy of core/shared is generated, never edited: these tests fail
 * when src/vendor no longer matches what scripts/vendor-core.mjs would write
 * from packages/core and packages/shared today.
 */
import assert from "node:assert/strict";
import fs from "node:fs";
import path from "node:path";
import { test } from "node:test";
import ts from "typescript";
import { REPO_DIR, VENDOR_DIR, generateVendor, vendorDrift } from "./vendor-core.mjs";

const generated = generateVendor();

test("src/vendor matches packages/core and packages/shared", () => {
  assert.deepEqual(vendorDrift(generated), [], "Run `pnpm vendor:raycast` and commit the result.");
});

/** Source text with the GENERATED header and every module specifier line dropped. */
function body(text) {
  const sf = ts.createSourceFile("x.ts", text, ts.ScriptTarget.Latest, true);
  let out = text;
  const spans = sf.statements
    .filter((st) => (ts.isImportDeclaration(st) || ts.isExportDeclaration(st)) && st.moduleSpecifier)
    .map((st) => [st.getStart(sf), st.end])
    .sort((a, b) => b[0] - a[0]);
  for (const [start, end] of spans) out = out.slice(0, start) + out.slice(end);
  return out.replace(/^\/\/ GENERATED by [^\n]*\n\/\/ Do not edit[^\n]*\n/, "").replace(/\n{2,}/g, "\n");
}

test("vendored files are the source files apart from the header and import lines", () => {
  for (const [file, content] of generated.files) {
    if (file === path.join(VENDOR_DIR, "index.ts")) continue;
    const rel = path.relative(VENDOR_DIR, file);
    const [pkg, ...rest] = rel.split(path.sep);
    const source = path.join(REPO_DIR, "packages", pkg, "src", ...rest);
    assert.equal(body(content), body(fs.readFileSync(source, "utf8")), rel);
    assert.ok(content.startsWith(`// GENERATED by packages/raycast/scripts/vendor-core.mjs from packages/${pkg}/src/`));
  }
});

test("no vendored file imports a workspace package", () => {
  for (const [file, content] of generated.files) {
    assert.doesNotMatch(content, /from\s+["']@starter\//, path.relative(VENDOR_DIR, file));
  }
});

/**
 * Vendored files the commands may load `zod` through at runtime. Core's
 * `stored-*.ts` readers validate what a cache on the device holds, which is
 * why `zod` is a runtime dependency of the extension. Anything else reaching
 * `zod` at runtime is a type-only file imported by value (shared/members.ts,
 * shared/einvoice.ts) and drags schemas nobody runs into every bundle; adding
 * a file here is a decision to argue in the diff.
 */
const RUNTIME_ZOD_FILES = new Set(["core/stored-catalog.ts", "core/stored-entry.ts"]);

test("the extension reaches zod at runtime only through the stored-data readers", () => {
  // Walk value (non-type) imports from the index.
  const seen = new Set();
  const visit = (file) => {
    if (seen.has(file)) return;
    seen.add(file);
    const text = generated.files.get(file);
    assert.ok(text !== undefined, `${file} is not generated`);
    const rel = path.relative(VENDOR_DIR, file).split(path.sep).join("/");
    const sf = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true);
    for (const st of sf.statements) {
      if (!(ts.isImportDeclaration(st) || ts.isExportDeclaration(st)) || !st.moduleSpecifier) continue;
      const typeOnly = ts.isImportDeclaration(st)
        ? st.importClause?.isTypeOnly ||
          (st.importClause?.namedBindings &&
            ts.isNamedImports(st.importClause.namedBindings) &&
            !st.importClause.name &&
            st.importClause.namedBindings.elements.every((el) => el.isTypeOnly))
        : st.isTypeOnly;
      if (typeOnly) continue;
      const spec = st.moduleSpecifier.text;
      if (spec === "zod") assert.ok(RUNTIME_ZOD_FILES.has(rel), `${rel} imports zod at runtime`);
      if (spec.startsWith(".")) visit(path.resolve(path.dirname(file), spec).replace(/\.js$/, ".ts"));
    }
  };
  visit(path.join(VENDOR_DIR, "index.ts"));
});

test("zod is a runtime dependency, because the stored-data readers run it", () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(VENDOR_DIR, "../../package.json"), "utf8"));
  assert.ok(pkg.dependencies?.zod, "packages/raycast/package.json must list zod under dependencies");
  assert.equal(pkg.devDependencies?.zod, undefined);
});

test("generation is deterministic", () => {
  const again = generateVendor();
  assert.deepEqual([...again.files.keys()], [...generated.files.keys()]);
  for (const [file, content] of again.files) assert.equal(content, generated.files.get(file));
});
