#!/usr/bin/env node
/**
 * Generates `packages/raycast/src/vendor/` — the copy of `@starter/core` and
 * `@starter/shared` the Raycast extension builds from.
 *
 * Why a copy at all: the Raycast Store builds an extension from its own folder
 * in raycast/extensions with `npm ci`, where `workspace:*` cannot resolve. So
 * the extension imports its core logic from `src/vendor/index.ts`, in the
 * monorepo and in the store alike, and this script is the only thing that
 * writes that directory. `packages/core` and `packages/shared` stay the single
 * source of truth: edit them, then run `pnpm vendor:raycast`.
 *
 * What it does, deterministically:
 *   1. Reads every `import … from "<…>/vendor/index.js"` in the extension's own
 *      sources and collects the names.
 *   2. Resolves each name through `packages/core/src/index.ts` (which re-exports
 *      `@starter/shared`) to the file that declares it.
 *   3. Follows those files' imports: relative ones are copied as they are, and
 *      every `@starter/shared` import is rewritten to name the declaring file
 *      inside `vendor/shared/`, so no barrel (and no zod schema a barrel would
 *      drag along) is pulled in.
 *   4. Writes each file with a GENERATED header and otherwise byte-for-byte,
 *      plus an `index.ts` exporting exactly the names the extension uses —
 *      `export type` for names with no runtime value.
 *
 * Usage:
 *   node scripts/vendor-core.mjs           # (re)write src/vendor
 *   node scripts/vendor-core.mjs --check   # exit 1 when src/vendor is stale
 */
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import ts from "typescript";

const HERE = path.dirname(fileURLToPath(import.meta.url));
export const RAYCAST_DIR = path.resolve(HERE, "..");
export const REPO_DIR = path.resolve(RAYCAST_DIR, "../..");
const SRC_DIR = path.join(RAYCAST_DIR, "src");
export const VENDOR_DIR = path.join(SRC_DIR, "vendor");
const VENDOR_INDEX = path.join(VENDOR_DIR, "index.ts");

/** Workspace packages that are vendored, and where their sources live. */
const PACKAGES = {
  core: path.join(REPO_DIR, "packages/core/src"),
  shared: path.join(REPO_DIR, "packages/shared/src"),
};
const CORE_INDEX = path.join(PACKAGES.core, "index.ts");
const SHARED_INDEX = path.join(PACKAGES.shared, "index.ts");

const toPosix = (p) => p.split(path.sep).join("/");
const repoRel = (p) => toPosix(path.relative(REPO_DIR, p));

function header(sourceFile) {
  return (
    `// GENERATED by packages/raycast/scripts/vendor-core.mjs from ${repoRel(sourceFile)}.\n` +
    `// Do not edit. Change the source file, then run \`pnpm vendor:raycast\`.\n`
  );
}

function listSources(dir) {
  const out = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      if (full === VENDOR_DIR) continue;
      out.push(...listSources(full));
    } else if (/\.tsx?$/.test(entry.name) && !entry.name.endsWith(".d.ts")) {
      out.push(full);
    }
  }
  return out.sort();
}

/** `./x.js` from `from` → absolute `.ts`/`.tsx` path. */
function resolveRelative(from, spec) {
  const base = path.resolve(path.dirname(from), spec);
  const stem = base.replace(/\.(js|jsx|mjs)$/, "");
  for (const candidate of [`${stem}.ts`, `${stem}.tsx`, path.join(base, "index.ts")]) {
    if (fs.existsSync(candidate)) return candidate;
  }
  throw new Error(`Cannot resolve "${spec}" from ${repoRel(from)}`);
}

function vendorPathFor(sourceFile) {
  for (const [name, dir] of Object.entries(PACKAGES)) {
    const rel = path.relative(dir, sourceFile);
    if (!rel.startsWith("..") && !path.isAbsolute(rel)) return path.join(VENDOR_DIR, name, rel);
  }
  throw new Error(`${repoRel(sourceFile)} is outside the vendored packages`);
}

function importPath(fromFile, toFile) {
  let rel = toPosix(path.relative(path.dirname(fromFile), toFile)).replace(/\.tsx?$/, ".js");
  if (!rel.startsWith(".")) rel = `./${rel}`;
  return rel;
}

function moduleDeclarations(sourceFile) {
  return sourceFile.statements.filter(
    (st) => (ts.isImportDeclaration(st) || ts.isExportDeclaration(st)) && st.moduleSpecifier,
  );
}

/** Names the extension imports from the vendor index. */
function collectRequestedNames() {
  const names = new Set();
  for (const file of listSources(SRC_DIR)) {
    const text = fs.readFileSync(file, "utf8");
    const sf = ts.createSourceFile(file, text, ts.ScriptTarget.Latest, true);
    for (const st of moduleDeclarations(sf)) {
      const spec = st.moduleSpecifier.text;
      if (spec.startsWith("@starter/")) {
        throw new Error(
          `${repoRel(file)} imports "${spec}". The extension must import core logic from src/vendor/index.js, ` +
            `or the store build cannot resolve it.`,
        );
      }
      if (!spec.startsWith(".")) continue;
      // Resolved by path rather than on disk: the index may not exist yet.
      const target = path.resolve(path.dirname(file), spec).replace(/\.js$/, ".ts");
      if (target !== VENDOR_INDEX) {
        if (target.startsWith(VENDOR_DIR + path.sep)) {
          throw new Error(`${repoRel(file)} imports "${spec}". Import from src/vendor/index.js only.`);
        }
        continue;
      }
      if (ts.isExportDeclaration(st)) throw new Error(`${repoRel(file)} re-exports the vendor index.`);
      const clause = st.importClause;
      const bindings = clause?.namedBindings;
      if (!clause || clause.name || !bindings || !ts.isNamedImports(bindings)) {
        throw new Error(`${repoRel(file)}: only named imports from the vendor index are supported.`);
      }
      for (const el of bindings.elements) names.add((el.propertyName ?? el.name).text);
    }
  }
  return [...names].sort();
}

function createProgram() {
  const options = {
    target: ts.ScriptTarget.ES2022,
    module: ts.ModuleKind.ESNext,
    moduleResolution: ts.ModuleResolutionKind.Bundler,
    skipLibCheck: true,
    noEmit: true,
    types: [],
    paths: { "@starter/shared": [SHARED_INDEX], "@starter/shared/*": [path.join(PACKAGES.shared, "*")] },
  };
  return ts.createProgram([CORE_INDEX], options);
}

function resolveSymbol(checker, symbol) {
  return symbol.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(symbol) : symbol;
}

/** The single source file that declares `symbol`, or a thrown error. */
function declaringFile(symbol, what) {
  const files = new Set((symbol.declarations ?? []).map((d) => d.getSourceFile().fileName));
  if (files.size !== 1) {
    throw new Error(`${what} is declared in ${files.size} files (${[...files].map(repoRel).join(", ")})`);
  }
  return path.resolve([...files][0]);
}

/**
 * @returns {{ files: Map<string, string>, externals: string[] }}
 *   `files` maps an absolute path under src/vendor to its full content.
 */
export function generateVendor() {
  const requested = collectRequestedNames();
  const program = createProgram();
  const checker = program.getTypeChecker();
  const coreIndex = program.getSourceFile(CORE_INDEX);
  if (!coreIndex) throw new Error("packages/core/src/index.ts did not load");
  const exportsByName = new Map(
    checker.getExportsOfModule(checker.getSymbolAtLocation(coreIndex)).map((s) => [s.name, s]),
  );

  // index.ts: file → { values, types }
  const indexEntries = new Map();
  const queue = [];
  const seen = new Set();
  const enqueue = (file) => {
    if (!seen.has(file)) {
      seen.add(file);
      queue.push(file);
    }
  };

  for (const name of requested) {
    const exported = exportsByName.get(name);
    if (!exported) throw new Error(`"${name}" is imported from the vendor index but @starter/core does not export it`);
    const symbol = resolveSymbol(checker, exported);
    const file = declaringFile(symbol, `"${name}"`);
    vendorPathFor(file);
    const entry = indexEntries.get(file) ?? { values: [], types: [] };
    (symbol.flags & ts.SymbolFlags.Value ? entry.values : entry.types).push(name);
    indexEntries.set(file, entry);
    enqueue(file);
  }

  const files = new Map();
  const externals = new Set();

  while (queue.length > 0) {
    const file = queue.shift();
    const sf = program.getSourceFile(file);
    if (!sf) throw new Error(`${repoRel(file)} is not part of the core program`);
    const dest = vendorPathFor(file);
    if (/import\(\s*["']@starter\//.test(sf.text)) {
      throw new Error(`${repoRel(file)} uses an import("@starter/…") type; name the file instead.`);
    }
    const edits = [];
    for (const st of moduleDeclarations(sf)) {
      const spec = st.moduleSpecifier.text;
      if (spec.startsWith(".")) {
        enqueue(resolveRelative(file, spec));
        continue;
      }
      if (!spec.startsWith("@starter/")) {
        externals.add(spec.startsWith("@") ? spec.split("/").slice(0, 2).join("/") : spec.split("/")[0]);
        continue;
      }
      if (spec !== "@starter/shared" && !spec.startsWith("@starter/shared/")) {
        throw new Error(`${repoRel(file)} imports "${spec}", which is not vendored`);
      }
      const isImport = ts.isImportDeclaration(st);
      const clause = isImport ? st.importClause : undefined;
      const named = isImport ? clause?.namedBindings : st.exportClause;
      if ((isImport && (!clause || clause.name)) || !named || !(ts.isNamedImports(named) || ts.isNamedExports(named))) {
        throw new Error(`${repoRel(file)}: only named imports/exports of "${spec}" can be vendored`);
      }
      const statementTypeOnly = isImport ? clause.isTypeOnly : st.isTypeOnly;
      const groups = new Map();
      for (const el of named.elements) {
        const symbol = resolveSymbol(checker, checker.getSymbolAtLocation(el.name));
        const target = declaringFile(symbol, `"${(el.propertyName ?? el.name).text}" in ${repoRel(file)}`);
        enqueue(target);
        const rel = importPath(dest, vendorPathFor(target));
        const text =
          (el.isTypeOnly ? "type " : "") + (el.propertyName ? `${el.propertyName.text} as ` : "") + el.name.text;
        groups.set(rel, [...(groups.get(rel) ?? []), text]);
      }
      const keyword = isImport ? "import" : "export";
      const replacement = [...groups]
        .map(([rel, names]) => {
          // A group of inline `type` names becomes `import type { … }`, so the
          // bundler never keeps a type-only file (and its zod import) as a
          // side-effect import.
          const allTypes = statementTypeOnly || names.every((n) => n.startsWith("type "));
          const list = allTypes ? names.map((n) => n.replace(/^type /, "")) : names;
          return `${keyword} ${allTypes ? "type " : ""}{ ${list.join(", ")} } from "${rel}";`;
        })
        .join("\n");
      edits.push([st.getStart(sf), st.end, replacement]);
    }
    let text = sf.text;
    for (const [start, end, replacement] of edits.sort((a, b) => b[0] - a[0])) {
      text = text.slice(0, start) + replacement + text.slice(end);
    }
    files.set(dest, header(file) + text);
  }

  let index =
    `// GENERATED by packages/raycast/scripts/vendor-core.mjs. Do not edit.\n` +
    `// The names the extension imports from @starter/core, resolved to the files that\n` +
    `// declare them. Run \`pnpm vendor:raycast\` after changing packages/core or packages/shared.\n`;
  const sortedIndex = [...indexEntries].sort(([a], [b]) => repoRel(a).localeCompare(repoRel(b)));
  for (const [file, { values, types }] of sortedIndex) {
    const rel = importPath(VENDOR_INDEX, vendorPathFor(file));
    if (values.length) index += `export { ${values.sort().join(", ")} } from "${rel}";\n`;
    if (types.length) index += `export type { ${types.sort().join(", ")} } from "${rel}";\n`;
  }
  files.set(VENDOR_INDEX, index);

  const sorted = new Map([...files].sort(([a], [b]) => a.localeCompare(b)));
  return { files: sorted, externals: [...externals].sort() };
}

function listVendorOnDisk() {
  if (!fs.existsSync(VENDOR_DIR)) return [];
  const walk = (dir) =>
    fs
      .readdirSync(dir, { withFileTypes: true })
      .flatMap((e) => (e.isDirectory() ? walk(path.join(dir, e.name)) : [path.join(dir, e.name)]));
  return walk(VENDOR_DIR).sort();
}

/** Differences between the generated copy and src/vendor on disk, as messages. */
export function vendorDrift(generated = generateVendor()) {
  const problems = [];
  for (const [file, content] of generated.files) {
    if (!fs.existsSync(file)) problems.push(`missing: ${repoRel(file)}`);
    else if (fs.readFileSync(file, "utf8") !== content) problems.push(`stale: ${repoRel(file)}`);
  }
  for (const file of listVendorOnDisk()) {
    if (!generated.files.has(file)) problems.push(`not generated (delete it): ${repoRel(file)}`);
  }
  const pkg = JSON.parse(fs.readFileSync(path.join(RAYCAST_DIR, "package.json"), "utf8"));
  const declared = { ...pkg.dependencies, ...pkg.devDependencies };
  for (const dep of generated.externals) {
    if (!declared[dep]) problems.push(`packages/raycast/package.json does not declare "${dep}", which vendored code imports`);
  }
  return problems;
}

export function writeVendor(generated = generateVendor()) {
  fs.rmSync(VENDOR_DIR, { recursive: true, force: true });
  for (const [file, content] of generated.files) {
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, content);
  }
  return generated;
}

if (import.meta.url === pathToFileURL(process.argv[1] ?? "").href) {
  const check = process.argv.includes("--check");
  try {
    const generated = generateVendor();
    if (check) {
      const problems = vendorDrift(generated);
      if (problems.length) {
        console.error("packages/raycast/src/vendor is out of date with packages/core and packages/shared:");
        for (const p of problems) console.error(`  ${p}`);
        console.error("Run `pnpm vendor:raycast` and commit the result.");
        process.exit(1);
      }
      console.log(`packages/raycast/src/vendor is up to date (${generated.files.size} files).`);
    } else {
      writeVendor(generated);
      console.log(`Wrote ${generated.files.size} files to packages/raycast/src/vendor.`);
    }
  } catch (error) {
    console.error(error instanceof Error ? error.message : error);
    process.exit(1);
  }
}
