import { defineConfig } from "eslint/config";
import raycastConfig from "@raycast/eslint-config";

export default defineConfig([
  // Generated by scripts/vendor-core.mjs from packages/core and packages/shared,
  // and kept byte-for-byte with them, so it follows their style, not this one.
  { ignores: ["src/vendor/**"] },
  ...raycastConfig,
]);
