/**
 * The docs site's self-hosting page against its source, `docs/self-hosting.md`.
 *
 * The docs-site copy is generated by `scripts/docs/sync-self-hosting.mjs` and
 * committed. What this guards: an edit to the guide that nobody re-synced,
 * which would leave the docs site serving the old install steps while GitHub
 * shows the new ones. The transform itself is checked on small inputs too,
 * because a broken link rewrite fails the docs build only much later.
 *
 * Run by the server package's `test` script (`pnpm test:unit`).
 */
import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { readFileSync } from "node:fs";
import { resolve } from "node:path";

import {
  BLOB_URL,
  REPO_ROOT,
  TARGET_PATH,
  renderFromRepo,
  renderSelfHostingDoc,
  rewriteTarget,
} from "../docs/sync-self-hosting.mjs";

describe("docs-site self-hosting page", () => {
  it("matches what scripts/docs/sync-self-hosting.mjs writes", () => {
    const committed = readFileSync(resolve(REPO_ROOT, TARGET_PATH), "utf8");
    assert.ok(
      committed === renderFromRepo(),
      `${TARGET_PATH} is out of date with docs/self-hosting.md. Run \`pnpm docs:sync\` and commit the result.`,
    );
  });
});

describe("renderSelfHostingDoc", () => {
  it("adds front matter and the generated-file note before the body", () => {
    const out = renderSelfHostingDoc("# Title\n\nBody.\n");
    assert.match(out, /^---\ntitle: .+\nsidebar_label: .+\ndescription: .+\n---\n\n<!-- Generated from docs\/self-hosting\.md .*pnpm docs:sync.* -->\n\n# Title\n/);
  });

  it("rewrites repo-relative links to GitHub and keeps anchors and URLs", () => {
    const out = renderSelfHostingDoc(
      [
        "See [`deploy.md`](./deploy.md), [the workflow](../.github/workflows/release.yml#L1),",
        "[a section](#backup-and-restore) and [Docker](https://docs.docker.com/).",
        "",
      ].join("\n"),
    );
    assert.ok(out.includes(`[\`deploy.md\`](${BLOB_URL}/docs/deploy.md)`));
    assert.ok(out.includes(`[the workflow](${BLOB_URL}/.github/workflows/release.yml#L1)`));
    assert.ok(out.includes("[a section](#backup-and-restore)"));
    assert.ok(out.includes("[Docker](https://docs.docker.com/)"));
  });

  it("escapes MDX syntax in prose but not in code", () => {
    const source = [
      "Replace <domain> with {your domain}, or `<domain>` and `{x}`.",
      "",
      "```bash",
      "curl https://<domain>/api/health # {json}",
      "```",
      "",
    ].join("\n");
    const out = renderSelfHostingDoc(source);
    assert.ok(out.includes("Replace &lt;domain> with \\{your domain\\}, or `<domain>` and `{x}`."));
    assert.ok(out.includes("curl https://<domain>/api/health # {json}"));
  });

  it("refuses a link that leaves the repository", () => {
    assert.throws(() => rewriteTarget("../../etc/passwd"), /leaves the repository/);
  });
});
